In [19]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as ptl

In [20]:
df = pd.read_csv("Churn_Modelling.csv", index_col=0)

In [21]:
df.duplicated().sum()

np.int64(0)

In [22]:
df.head()

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
RowNumber,,,,,,,,,,,,,
1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [24]:
df.drop(columns=['CustomerId', 'Surname'], axis=1, inplace=True)

In [25]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
RowNumber,,,,,,,,,,,
1,619,France,Female,42,2,0.00,1,1,1,101348.88,1
2,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
3,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
4,699,France,Female,39,1,0.00,2,0,0,93826.63,0
5,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [26]:
X = df.drop(columns=['Exited'], axis=1)
y = df['Exited']

In [31]:
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.compose import ColumnTransformer

cat_col = [col for col in X.columns if X[col].dtype == 'O']
num_col = [col for col in X.columns if X[col].dtype != 'O']

ct = ColumnTransformer([
    ("OneHotEncoding", OneHotEncoder(drop='first'), cat_col),
    ("StandardScaler", StandardScaler(), num_col)
])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

X_train = ct.fit_transform(X_train)
X_test = ct.transform(X_test)

In [32]:
from sklearn.metrics import accuracy_score, classification_report

model = LogisticRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred, target_names=['Stayed', 'Exited']))

Accuracy: 0.811
              precision    recall  f1-score   support

      Stayed       0.83      0.96      0.89      1607
      Exited       0.55      0.20      0.29       393

    accuracy                           0.81      2000
   macro avg       0.69      0.58      0.59      2000
weighted avg       0.78      0.81      0.77      2000